### ISSUE TITLE
Add search bar

### ISSUE THREAD

**Issue by LolaMaria** [LolaMaria/capstone-project#10]
### Value Proposition
**As a User**
**I need** to search for plants
**to be able to** find a plant faster

### Description

![UserStory6-2](https://user-images.githubusercontent.com/98463150/161726247-4f5ed495-0102-4fd1-af15-748d0a9d79ec.svg)

### Acceptance Criteria
- [ ] a search bar is displayed
- [ ] the searchbar makes it possible to find a plant by name

### Tasks 
- [ ] create a new branch `searchbar`
- [ ] create searchbar component
- [ ] create searchbar.spec
- [ ] create searchbar.stories
- [ ] update styles
- [ ] test on different browsers/devices
