### ISSUE TITLE
Image upload

### ISSUE THREAD

**Issue by LolaMaria** [LolaMaria/capstone-project#14]
### Value Proposition
**As a User**
**I need** to upload a picture to my created plant
**to be able to** visualise my plant and see a harmonic plant collection 

### Description
![UserStory7](https://user-images.githubusercontent.com/98463150/162640030-f505dc9f-d8ff-4732-87e7-6bee4b8dcf49.svg)

### Acceptance Criteria
- [x] an image upload field is displayed under the input fields
- [x] the field makes it possible to upload a picture into your created plant card

### Tasks 
- [x] create a new branch `image`
- [x] create image component
- [x] update styles
- [x] test on different browsers/devices
