### ISSUE TITLE
Filter plant cards

### ISSUE THREAD

**Issue by LolaMaria** [LolaMaria/capstone-project#15]
### Value Proposition
**As a User**
**I need** to filter plants
**to be able to** find a plant fitting to my needs

### Description
![UserStory8](https://user-images.githubusercontent.com/98463150/162640197-256fb5bc-1732-448c-9d2f-d15048c91ba5.svg)

### Acceptance Criteria
- [x] filter categories are displayed
- [x] checking selective categories shows the criteria fitting plants
- [x] a new navigation button is displayed

### Tasks 
- [x] create a new branch `filter`
- [x] create filter component
- [x] create new page and route
- [x] create new navigation button
- [x] update styles
- [x] test on different browsers/devices
