### ISSUE TITLE
Reminder

### ISSUE THREAD

**Issue by LolaMaria** [LolaMaria/capstone-project#19]
### Value Proposition
**As a User**
**I need** to set reminders
**to be able to** remind me of when to water my plants for example

### Description
![UserStory9](https://user-images.githubusercontent.com/98463150/164246397-430100bb-10b9-4754-85c1-b41e025a8b1c.svg)

### Acceptance Criteria
- [x] a form with two input fields is displayed
- [x] in one input you can select a date through a calendar
- [x] a new navigation button is displayed
- [x]  a submit button is displayed

### Tasks 
- [x] create a new branch `calendar`
- [x] create button component
- [x] create new reminder page and route
- [x] create new navigation button 'reminder'
- [x]  create submit button that submits the reminder 
- [x] update styles
- [x] test on different browsers/devices
