### ISSUE TITLE
Show Plant Cards

### ISSUE THREAD

**Issue by LolaMaria** [LolaMaria/capstone-project#2]
### Value Proposition
**As a User**
**I need** to see different kind of plants
**to be able to** decide which plants I like

### Description
![UserStory1](https://user-images.githubusercontent.com/98463150/159689922-e154de08-8a5a-4a8b-93d7-e3de859e5cd5.svg)

### Acceptance Criteria
- [x]  a header with the App name is displayed
- [x] different cards with plant information are displayed
 
### Tasks

- [x] create new branch `show-plants`
- [x] create a json with plant data
- [x] create Card component
- [x] create Card.spec
- [x] create Card.stories
- [x] display data in Cards
- [x] update styles 
- [x] test on different browsers/devices
