### ISSUE TITLE
Bookmarked plants

### ISSUE THREAD

**Issue by LolaMaria** [LolaMaria/capstone-project#3]
### Value Proposition
**As a User**
**I need** to bookmark a card
**to be able to** view them as a collection

### Description

![UserStory2-2](https://user-images.githubusercontent.com/98463150/159800196-64efec59-0a29-41d6-9a73-f999fd4bb903.svg)

### Acceptance Criteria

- [x] the cards have buttons as bookmarks
- [x] on click the bookmark is toggled and saved on another page
- [x] a navigation is displayed which leads you to the other page 

### Tasks
- [x] create new branch `bookmark`
- [x] create Button component
- [x] create Button.spec
- [x] create Button.stories
- [x] create Navigation component 
- [x] create Navigation.spec
- [x] create Navigation.stories
- [x] create a path to new page where bookmarks are saved (implement react router)
- [x] update styles 
- [x] test on different browsers/devices
