### ISSUE TITLE
Add Plant Cards

### ISSUE THREAD

**Issue by LolaMaria** [LolaMaria/capstone-project#4]
### Value Proposition
**As a User**
**I need** to create my own plant card
**to be able to** add it to my collection of plants

### Description
![UserStory3](https://user-images.githubusercontent.com/98463150/160129206-8afbc5b4-faba-4ffe-8dc8-68fd73b3102e.svg)

### Acceptance Criteria
- [x] inputs are displayed
- [x] whitespaces are trimmed
- [x] a submit button adds the new plant card to the plant site
- [x] a new navigation button is displayed

### Tasks 
- [x] create a new branch `create-plant`
- [x] create Input page
- [x] create submit button component
- [x]  create submitButton.spec
- [x] create submitButton.stories
- [x] add a new button to the navigation component
- [x] add route to "add plant" site
- [x] update styles
- [x] test on different browsers/devices
