### ISSUE TITLE
Add delete button and local storage

### ISSUE THREAD

**Issue by LolaMaria** [LolaMaria/capstone-project#8]

**Comment by LolaMaria** [comment]
### Value Proposition
**As a User**
**I need** to delete plant cards
**to be able to** have control over my plant collection and alter mistakes

### Description
![UserStory4](https://user-images.githubusercontent.com/98463150/161460696-8ecf58bf-792d-4285-b763-c85aa49d307e.svg)




### Acceptance Criteria
- [x] a delete button is displayed on plant cards
- [x] the button deletes card
- [x] local storage makes it possible to save changes


### Tasks 
- [x] create a new branch `delete-plant`
- [x] create delete button
- [x] create delete.spec
- [x] create delete.stories
- [x] add local storage functionality
- [x] update styles
- [x] test on different browsers/devices
