### ISSUE TITLE
Add edit button

### ISSUE THREAD

**Issue by LolaMaria** [LolaMaria/capstone-project#9]
### Value Proposition
**As a User**
**I need** to edit plant cards
**to be able to** alter mistakes or update information

### Description
![UserStory5](https://user-images.githubusercontent.com/98463150/161461313-9bc71213-c541-429f-b295-3f1e5e03c3a4.svg)

### Acceptance Criteria
- [x] an edit button is displayed on plant cards
- [x] the button makes it possible to edit the card

### Tasks 
- [x] create a new branch `edit-plant`
- [x] create edit button
- [x] create edit.spec
- [x] create edit.stories
- [x] update styles
- [x] test on different browsers/devices
